export default {
    borderRadius: 15,
    borderRadiusRound: 20,
    borderWidth: 2,
    borderWidthThick: 6,
    headerTop: 20,
    marginVertical: "3%",
    paddingVertical: "3%",
    marginHorizontal: "5%",
    paddingHorizontal: "5%",
    paddingLeft: "10%",
    marginUnderHeader: "20%",
    marginTopOrBottom: "10%",
    contentGap: "10%",
    width: "100%",
    height: "100%",
    elevation: 4,
}