export default {
    borderRadius: 5,
    borderRadiusRound: 20,
    borderWidth: 2,
    borderWidthThick: 6,
    headerTop: 20,
    marginVertical: "5%",
    paddingVertical: "3%",
    paddingVerticalLarge: "20%",
    marginHorizontal: "5%",
    paddingHorizontal: "5%",
    paddingVerticalSmall: 5,
    marginUnderHeader: "35%",
    contentGap: "10%",
    width: "100%",
    height: "100%",
}